# Chapter 4 - NumPy Basics: Arrays and Vectorized Computation

## 4.2 Universal Functions: Fast Element-Wise Array Functions

In [1]:
import numpy as np

A universal function or <i>ufunc</i> is a function that performs element-wise operations on data in `ndarray`s.

**Mathematical functions like  `square`, `sqrt`, `exp`, `abs`**

In [2]:
# p = np.random.randint(50, 100, (2,4))
p = np.array([[85, 71, 64, 83],
              [63, 74, 56, 52]])
print(np.square(p))
print()
print(np.sqrt(p))

[[7225 5041 4096 6889]
 [3969 5476 3136 2704]]

[[9.21954446 8.42614977 8.         9.11043358]
 [7.93725393 8.60232527 7.48331477 7.21110255]]


In [3]:
# q = np.random.ranf((2,3))
# a = np.random.randn(2,3)
q = np.array([[0.1057, 0.3118, 0.7330],
              [0.7803, 0.6197, 0.0032]])
print(np.exp(q))
print()

a = np.array([[-0.31571427, -0.13416209,  0.70521823],
              [ 1.26355913,  1.87158289,  0.07813458]])
print(np.abs(a))

[[1.11148838 1.36588149 2.0813152 ]
 [2.18212681 1.85837045 1.00320513]]

[[0.31571427 0.13416209 0.70521823]
 [1.26355913 1.87158289 0.07813458]]


**Simple transformations like `sign`, `ceil`, `floor`**

In [4]:
a = np.array([[-0.31571427, -0.13416209,  0.70521823],
              [ 1.26355913,  1.87158289,  0.07813458]])
# returns -1 if the value is negative, 1 if the value is positive and
# 0 if the value is 0
print(np.sign(a))
b = a*10
print()
print(b)
print()
print(np.ceil(b))
print()
print(np.floor(b))

[[-1. -1.  1.]
 [ 1.  1.  1.]]

[[-3.1571427 -1.3416209  7.0521823]
 [12.6355913 18.7158289  0.7813458]]

[[-3. -1.  8.]
 [13. 19.  1.]]

[[-4. -2.  7.]
 [12. 18.  0.]]


A binary universal function or <i>binary ufunc</i> takes in two arrays and returns a single array as a result.

Using **`maximum`, `minimum`, `floor_divide`**

In [5]:
# r, s = np.random.ranf((2,3)), np.random.ranf((2,3))
r = np.array([[0.2551, 0.4742, 0.8395,],
              [0.9259, 0.1304, 0.3548]])

s = np.array([[0.0284, 0.5225, 0.3913,],
              [0.7145, 0.7139, 0.8426],])

# Returns the maximum comparing element by element in 2 arrays
print(np.maximum(r, s))
print()
# Returns the minimum comparing element by element in 2 arrays
print(np.minimum(r, s))

[[0.2551 0.5225 0.8395]
 [0.9259 0.7139 0.8426]]

[[0.0284 0.4742 0.3913]
 [0.7145 0.1304 0.3548]]


In [6]:
s = np.array([[ 1., 26., 19.],
              [35., 35., 42.]])
# Gives the dividend without remainder
print(np.floor_divide(s, 4))

[[ 0.  6.  4.]
 [ 8.  8. 10.]]


Sometimes, a <i>ufunc</i> can return multiple arrays

**Using `modf`**

In [7]:
r = np.array([[1.2755, 2.371 , 4.1975],
              [4.6295, 0.652 , 1.774 ]])

# Returns the fractional and integer form of the array
w, m = np.modf(r)

# Returns any remainder value after removing the whole number portion
print(w)
print()
# Returns any residual after removing the whole number portion
print(m)

[[0.2755 0.371  0.1975]
 [0.6295 0.652  0.774 ]]

[[1. 2. 4.]
 [4. 0. 1.]]


<hr>

**References:**

Python for Data Analysis, 2nd Edition, McKinney (2017)